---
title: "RetMIP results"
output:
  html_document:
    highlight: textmate
    theme: spacelab
    toc: yes
  pdf_document:
    toc: yes
  html_notebook:
    toc: yes
  word_document:
    toc: yes
always_allow_html: yes
mathjax: null
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ncdf4)
library(ggplot2)
library(reshape)
library(functional)
library(pracma)
library(dplyr)
library(lubridate)
library(gridExtra)
library(grid)
library(viridis)
library(RColorBrewer)
 library(ggpubr)
 library(cowplot)
Sys.setlocale("LC_TIME", "English")

path_model<-'C:/Users/bav/OneDrive - Geological survey of Denmark and Greenland/Data/RetMIP/Model outputs/'
sites<-list('KANU','Dye-2_long','Dye-2_16','Summit','FA')
sites2<-list('KAN_U','Dye-2_long','Dye-2_16','Summit','FA')
models <- list('CFM-Cr','CFM-KM','DTU','DMIHH','GEUS','IMAUFDM','MeyerHewitt','UppsalaUniBucket','UppsalaUniDeepPerc',
               'SUTRAICE_70perm','SUTRAICE_700perm')
start_time <- c("01-May-2012 00:00:00","01-Jun-1998 00:00:00","02-May-2016 00:00:00","02-Jul-2000 00:00:00","12-Apr-2014 00:00:00")
end_time <- c("31-Dec-2016 06:00:00","02-May-2015 15:00:00","28-Oct-2016 09:00:00","08-Mar-2015 12:00:00","02-Dec-2014 21:00:00")
```

This document contains the scripts and plots for the RetMIP project (http://retain.geus.dk/index.php/retmip/).


```{r trunoff KANU yearly1}
multi_1D_plot <- function (i_site,i_mod=1:9, set_lim, multipl_fact=1,pal_name='Set1'){
  for (ii in i_mod){
    file_name_val <- paste('RetMIP_',models[ii],'_',sites[i_site],'_3hourly_values.nc',sep = "")
    path_file_val <- paste(path_model,models[ii],'/',file_name_val,sep = "")
    file_nc_val<- nc_open(path_file_val)
  # extracting variable
    trfrz   <- ncvar_get(file_nc_val, varid = "trfrz")    
    trfrz <- trfrz[!is.na(trfrz)]
    trunoff   <- ncvar_get(file_nc_val, varid = "trunoff")
    trunoff <- trunoff[!is.na(trunoff)]
    
    if (models[ii] %in% c("CFM-Cr","CFM-KM","GEUS")) {
      trfrz <- trfrz * 1000
      trunoff <- trunoff * 1000
    }
  
    if (strcmp(models[[ii]],"IMAUFDM")) {
      trfrz <- pmax(trfrz,0)
      trunoff <- pmax(trunoff,0) }    
    if (ii==7 & i_site==2) { trfrz <- -trfrz
    trfrz[trfrz>10] <- 10}
    
    # if(missing(set_lim)) {set_lim<- c(0,max(trfrz))}
    
    # reconstructing time
    nc_close(file_nc_val)
     time1<-1:length(trfrz)
      date_mod<-seq(lubridate::dmy_hms(start_time[i_site]),
                    lubridate::dmy_hms(end_time[i_site]), 3600*3)
      
    if (length(date_mod)<length(time1)) {
      trfrz<-trfrz[- (1:(length(time1)-length(date_mod)))]
      trunoff<-trunoff[- (1:(length(time1)-length(date_mod)))]
      time1  <- time1[- (1:(length(time1)-length(date_mod)))]}
    
    while (length(date_mod)>length(time1)) {
      trfrz <- append(trfrz, NaN*trfrz[length(time1)-1])
      trunoff <- append(trunoff, NaN*trunoff[length(time1)-1])
      time1 <- append(time1, time1[length(time1)]+3600*3)}
      
    year_list <- unique(year(date_mod))
    
    if (ii == i_mod[1]) {
      df <- data.frame(date_mod,month(date_mod), year(date_mod))
        colnames(df)[2] <- "month"
        colnames(df)[3] <- "year"
      df_rfrz <- df
      df_runoff <- df } 
    
    df_rfrz[models[[ii]][1]] <- trfrz
    df_runoff[models[[ii]][1]] <- trunoff
  }
  
  df_m <- melt(df,id.vars = c(1,2,3))
  df_rfrz_m <- melt(df_rfrz,id.vars = c(1,2,3))
  df_runoff_m <- melt(df_runoff,id.vars = c(1,2,3))

  get_palette<- colorRampPalette(brewer.pal(brewer.pal.info[ pal_name,1], pal_name))
  cbp1<-get_palette(9)
  
  # Plotting
  df_year <- data.frame(unique(df_runoff$year))
  colnames(df_year)[1] <- "year"
  df_rfrz_year <- df_year
  df_runoff_year <- df_year
  df_check <- df_year
  for (i in i_mod){
    df_rfrz_year[,models[[i]][1]] <- accumarray(df$year-df$year[1]+1, df_rfrz[,models[[i]][1]],
                                           func=function (x) {sum(x,na.rm=TRUE)})
    df_runoff_year[,models[[i]][1]] <- accumarray(df$year-df$year[1]+1, df_runoff[,models[[i]][1]],
                                           func=function (x) {sum(x,na.rm=TRUE)})
     df_year[,models[[i]][1]] <- df_rfrz_year[,models[[i]][1]]/
      (df_runoff_year[,models[[i]][1]]+df_rfrz_year[,models[[i]][1]]) *100
     df_check[,models[[i]][1]] = df_rfrz_year[,models[[i]][1]] + df_runoff_year[,models[[i]][1]]
  }
  df_summary =data.frame(df_rfrz_year$year)
  df_summary <- transform(df_summary, rfrz_avg=apply(df_rfrz_year[,c(-1,-4)],1, mean, na.rm = TRUE))      
  df_summary <- transform(df_summary, rfrz_2sig=apply(df_rfrz_year[,c(-1,-4)],1, sd, na.rm = TRUE))
  df_summary$rfrz_2sig <- df_summary$rfrz_2sig*2
  df_summary <- transform(df_summary, rfrz_avg_pct=apply(df_year[,c(-1,-4)],1, mean, na.rm = TRUE))      
  df_summary <- transform(df_summary,  rfrz_2sig_pct=apply(df_year[,c(-1,-4)], 1, sd, na.rm = TRUE))
  df_summary$rfrz_2sig_pct <- df_summary$rfrz_2sig_pct*2

  df_summary <- transform(df_summary, runoff_avg=apply(df_runoff_year[,c(-1,-4)],1, mean, na.rm = TRUE))
  df_summary <- transform(df_summary, runoff_2sig=apply(df_runoff_year[,c(-1,-4)],1, sd, na.rm = TRUE))
  df_summary$runoff_2sig <- df_summary$runoff_2sig*2
  df_summary <- transform(df_summary, runoff_avg_pct=apply(100-df_year[,c(-1,-4)],1, mean, na.rm = TRUE))
  df_summary <- transform(df_summary, runoff_2sig_pct=apply(100-df_year[,c(-1,-4)], 1, sd, na.rm = TRUE))
  df_summary$runoff_2sig_pct <- df_summary$runoff_2sig_pct*2

  print(df_summary)

  df_year_m <- melt(df_year,id.vars = 1)
  df_rfrz_m <- melt(df_rfrz_year,id.vars = 1)
  df_runoff_m <- melt(df_runoff_year,id.vars = 1)
  mean_2se <- function (x) 
  { x <- stats::na.omit(x)
    se <- 2 * sqrt(stats::var(x))
    mean <- mean(x)
    return(list(y = mean, ymin = max(0, mean - se), ymax = mean + 
      se)) }
   
  plot_func <- function(df,y_lab_text){
    df2<-df
    df2$value[which(df2$variable=="DTU")]<-NA
  
    h <- ggplot(data = df2, 
              aes(x=factor(year), y = value, colour=variable))+
              stat_summary(fun = mean, geom = "point",shape = 4, stroke=1.5,color="black",size=2.5) + 
              stat_summary(fun.data = mean_2se, geom = "errorbar",color="black",size=1)+  
              geom_point(data = df, 
                    aes(x=factor(year), y = value, colour=variable), 
                    shape = 19, position=position_jitterdodge(),  cex=2,alpha=0.9)+
              ggtitle(sites2[[i_site]])+
              labs(x = "Year",  y =  y_lab_text, colour="")+
              scale_fill_manual(values = cbp1)+
              scale_colour_manual(values = cbp1)+
              scale_y_continuous(expand=c(0.1,0.1))+
              theme(legend.position = "none",
                    panel.background = element_blank(),
                      axis.line = element_line(colour = "black"),
                      panel.border = element_rect(colour = "black", fill=NA, size=1),
                    legend.key=element_rect(colour=NA,fill=NA))
  }
   h_rfrz <- plot_func(df_rfrz_m,"Refreezing \n(mm w.e.)") +
                  theme(axis.title.x=element_blank(), axis.text.x=element_blank())
   h_runoff <- plot_func(df_runoff_m,"Runoff \n(mm w.e.)") +
                  theme(plot.title = element_blank(),axis.title.x=element_blank(), axis.text.x=element_blank())  
   mean_2se <- function (x) 
      { x <- stats::na.omit(x)
        se <- 2 * sqrt(stats::var(x))
        return(list(y = mean(x), ymin = max(0,mean(x) - se), ymax = min(100, mean(x) + se))) }
   h_fraction <- plot_func(df_year_m,"Refreezing \n(%)") +
                  scale_y_continuous(sec.axis = sec_axis(~100-.*1,  name = "Runoff (%)"),expand=c(0.1,0.1))+
                   guides(colour=guide_legend(ncol=3))+
                     theme(plot.title = element_blank(),legend.position = "right")
  mylegend<-as_ggplot(get_legend(h_fraction))
  h_fraction<-h_fraction +theme(legend.position = "none")

    plots = list(mylegend, h_fraction, h_rfrz, h_runoff)
    return(plots) 
}

plots_KAN_U <- multi_1D_plot(i_site=1)
plots_Dye2 <- multi_1D_plot(i_site=2)
mylegend <-plots_KAN_U[[1]]
plots_KAN_U[[1]]<-NULL
plots_Dye2[[1]]<-NULL
my_labs <- 1998:2015
my_labs <- as.character(my_labs)
for (i in seq(2,18,2)){my_labs[i] = ""}
plots_Dye2[[1]]<-plots_Dye2[[1]]+
  scale_x_discrete(labels=my_labs)
plot_list = list(plots_Dye2[[2]], plots_KAN_U[[2]], 
                 plots_Dye2[[3]], plots_KAN_U[[3]], 
                 plots_Dye2[[1]], plots_KAN_U[[1]])

h <- plot_grid(mylegend,plot_grid(plotlist = plot_list, 
                                  align = "v",labels=c("a)","d)","b)","e)","c)","f)"), 
                                  nrow=3,rel_heights = c(1,0.85,1.05)),
               ncol=1,rel_heights = c(0.2,1))

h
ggsave(filename=paste0("Plots/runoff_rfrz.jpg"),
             plot=h,width = 20, height = 15, units = "cm",device = "jpeg")
```


```{r Percolation depth}
# loading data
file_path <- "C:\\Users\\bav\\OneDrive - Geological survey of Denmark and Greenland\\Data\\RetMIP\\Validation datasets\\UpGPR_Dye2_Heilig\\"
filename <- "PercolationDepth_m_Perco2016.csv"
d_perc <- read.table(paste0(file_path,filename), header = FALSE, sep = ",", dec = ".")
d_perc$time <-     as.POSIXct((d_perc$V1 - 719529)*86400, origin = "1970-01-01", tz = "UTC")

i_site <- 3
var_name <- 'lwc'
offset <- 0
multipl_fact<-1

 for (i_mod in 1:9){
    file_name_col <- paste('RetMIP_',models[i_mod],'_',sites[i_site],'_3hourly_columns.nc',sep = "")
    path_file_col<-paste(path_model,models[i_mod],'/',file_name_col,sep = "")
    
    # loading column data
    file_nc_col<- nc_open(path_file_col)
    var_mod <- ncvar_get(file_nc_col, varid=var_name)
    var_mod <- var_mod + offset
    var_mod <- var_mod *multipl_fact
    
    if (i_mod == 6)
      {var_mod <- var_mod[!is.na(var_mod[,1]),]}
    # if (i_mod == 5 & var_name == "temp")
    # {var_mod <- var_mod +273}
    
    if (i_mod == 5 & var_name == "lwc")
      { var_mod<- pmax(var_mod,0)}
    # {var_mod <- var_mod +273}
    
    if (i_mod %in% 1:3 & var_name == "lwc")
      { var_mod<- var_mod*1000}
    
    if (dim(var_mod)[1]>dim(var_mod)[2]) var_mod <- t(var_mod)
    
    time1<-1:dim(var_mod)[2]
    
    date_mod<-seq(lubridate::dmy_hms(start_time[i_site]),
      lubridate::dmy_hms(end_time[i_site]),
      3600*3)
    
    if (length(date_mod)<length(time1)) {
      var_mod<-var_mod[,- (1:(length(time1)-length(date_mod)))]
      time1  <- time1[- (1:(length(time1)-length(date_mod)))]}
    
    if (length(date_mod)>length(time1)) {
      print(length(date_mod))
      print(length(time1))
      time <- ncvar_get(file_nc_col, varid='time')
      time<- time*3600*24 + as.POSIXct("1900-01-01")
    }
    
    while (length(date_mod)>length(time1)) {
      time1 <- append(time1, time1[length(time1)]+3600*3)
      var_mod <- cbind(var_mod, var_mod[,length(time1)-1])}
    
    # some filtering
    # var_mod<-var_mod[apply(var_mod, 1, Compose(is.finite, all)),]
    
    # rearranging in xyz array
    ind_select<-seq(1,dim(var_mod)[2],max(1,floor(dim(var_mod)[2]/1000)))
    time_select <- date_mod[ind_select]
    var_mod<-var_mod[,ind_select]
    d_perc_mod  <- var_mod[1,ind_select]*0
    depth <- seq(0.1, 20, 0.1)
     for (i in 1:length(d_perc_mod)){
       if (length(which(var_mod[,i] > 0.0000001))>0)
         { ind <- max(which(var_mod[,i] > 0.0000001))
         d_perc_mod[i] <- depth[ind] }
     }
       
    if (i_mod==1) {
      df <- data.frame(time_select,cbind(d_perc_mod))
      colnames(df)[0] <- "time"} 
    else {df <- cbind(df,d_perc_mod)}
    colnames(df)[1+i_mod] <- models[i_mod]
  }

pal_name <- "Set1"

perc_df <- df
perc_df_m <- melt(df,id.vars = 1)
lims <- as.POSIXct(strptime(c("2016-05-01 00:00", "2016-10-01 00:00"), 
                   format = "%Y-%m-%d %H:%M"),origin = "1970-01-01")

get_palette<- colorRampPalette(brewer.pal(brewer.pal.info[ pal_name,1], pal_name))
cbp1<-get_palette(9)

g <- ggplot(data = perc_df_m, aes(x = time_select, y = value, color  = variable)) +
      geom_line(data = d_perc, aes(x = time, y = V2, lty = "Up-GPR"), color = "black", size = 2)+
    geom_line(size=1,alpha=0.9) + 
      scale_y_continuous(trans = "reverse", expand = c(0, 0.1)) +
      scale_x_datetime(date_labels="%b-%y",limits=lims, expand = c(0, 0)) +
  grids()+
      labs(x = "Date", 
           y =  "Percolation depth (m)",
           color="Models",
           shape = "Observation")+
      scale_color_manual(values = cbp1)+
      theme(panel.background = element_blank(),
              axis.line = element_line(colour = "black"),
              panel.border = element_rect(colour = "black", fill=NA, size=1),
            legend.key=element_rect(colour=NA,fill=NA),
            legend.title = element_blank(),
            legend.spacing.x = unit(0.3,"cm")) 
      plot(g)
    
      ggsave(filename="Plots/percolation.jpeg",
             plot=g,  width = 20, height = 8, dpi = 300, units = "cm")


```







