---
title: "RetMIP results"
output:
  html_document:
    highlight: textmate
    theme: spacelab
    toc: yes
  pdf_document:
    toc: yes
  html_notebook:
    toc: yes
  word_document:
    toc: yes
always_allow_html: yes
mathjax: null
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ncdf4)
library(ggplot2)
library(reshape)
library(functional)
library(pracma)
library(dplyr)
library(lubridate)
library(gridExtra)
library(grid)
library(viridis)
library(RColorBrewer)
 library(ggpubr)
 library(cowplot)
Sys.setlocale("LC_TIME", "English")

path_model<-'C:/Users/bav/OneDrive - Geological survey of Denmark and Greenland/Data/RetMIP/Model outputs/'
sites<-list('KANU','Dye-2_long','Dye-2_16','Summit','FA')
models <- list('CFM-Cr','CFM-KM','DTU','DMIHH','GEUS','IMAUFDM','MeyerHewitt','UppsalaUniBucket','UppsalaUniDeepPerc')
start_time <- c("01-May-2012 00:00:00","01-Jun-1998 00:00:00","02-May-2016 00:00:00","02-Jul-2000 00:00:00","12-Apr-2014 00:00:00")
end_time <- c("31-Dec-2016 06:00:00","02-May-2015 15:00:00","28-Oct-2016 09:00:00","08-Mar-2015 12:00:00","02-Dec-2014 21:00:00")
```

This document contains the scripts and plots for the RetMIP project (http://retain.geus.dk/index.php/retmip/).



```{r multiplot 1D}
# ==== Plotting 1D ====

multi_1D_plot <- function (i_site,i_mod, var_name, set_lim, multipl_fact,opt,pal_name){
  
  if(missing(multipl_fact)) {
        multipl_fact<-1
  }
  if(missing(pal_name)) {
        pal_name<-'Set1'
  }
  if(missing(opt)) {
        opt<-"normal"
  }

    for (ii in i_mod){
    file_name_val <- paste('RetMIP_',models[ii],'_',sites[i_site],'_3hourly_values.nc',sep = "")
    path_file_val <- paste(path_model,models[ii],'/',file_name_val,sep = "")

    file_nc_val<- nc_open(path_file_val)

  # extracting variable
    var_mod   <- ncvar_get(file_nc_val, varid = var_name)
    trfrz   <- ncvar_get(file_nc_val, varid = "trfrz")
    trunoff   <- ncvar_get(file_nc_val, varid = "trunoff")
      #Remove NA values
  var_mod <- var_mod[!is.na(var_mod)]
  trunoff <- trunoff[!is.na(trunoff)]
  trfrz <- trfrz[!is.na(trfrz)]
  #   t_water <- (trunoff+trfrz)
  # var_mod[t_water>0] <- var_mod[t_water>0]  / (trunoff[t_water>0] +trfrz[t_water>0] ) *100
  var_mod <- var_mod*multipl_fact
  
  if (var_name %in% c("trfrz", "tlwc","trunoff")){
    if (models[ii] %in% c("CFM-Cr","CFM-KM","GEUS")) {
      var_mod <- var_mod * 1000
      trfrz <- trfrz * 1000
      trunoff <- trunoff * 1000
    }
  }

        if (strcmp(models[[ii]],"IMAUFDM")) {
    var_mod <- pmax(var_mod,0)
    trfrz <- pmax(trfrz,0)
    trunoff <- pmax(trunoff,0)
    }

  
    if(missing(set_lim)) {
          set_lim<- c(0,max(var_mod))
    }
  
  # reconstructing time
   # tryCatch(time1  <- ncvar_get(file_nc_val, varid = "time"), finally = time1  <- file_nc_val$dim$time$vals)
  nc_close(file_nc_val)

  # date_mod <- as.POSIXct("1900-01-01") + time_mod*3600*24
   time1<-1:length(var_mod)
    
    date_mod<-seq(lubridate::dmy_hms(start_time[i_site]),
                  lubridate::dmy_hms(end_time[i_site]),
                  3600*3)
    
  
    if (length(date_mod)<length(time1)) {
      var_mod<-var_mod[- (1:(length(time1)-length(date_mod)))]
      trfrz<-trfrz[- (1:(length(time1)-length(date_mod)))]
      trunoff<-trunoff[- (1:(length(time1)-length(date_mod)))]
      time1  <- time1[- (1:(length(time1)-length(date_mod)))]}
  

      while (length(date_mod)>length(time1)) {
        var_mod <- append(var_mod, NaN*var_mod[length(time1)-1])
        trfrz <- append(trfrz, NaN*trfrz[length(time1)-1])
        trunoff <- append(trunoff, NaN*trunoff[length(time1)-1])
        time1 <- append(time1, time1[length(time1)]+3600*3)}
    
  year_list <- unique(year(date_mod))
  
  if (ii == i_mod[1]) {
    df <- data.frame(date_mod,month(date_mod), year(date_mod))
      colnames(df)[2] <- "month"
      colnames(df)[3] <- "year"
    df_rfrz <- df
    df_runoff <- df
  } 


  df[models[[ii]][1]] <- var_mod
  df_rfrz[models[[ii]][1]] <- trfrz
  df_runoff[models[[ii]][1]] <- trunoff
  }
  
  df_m <- melt(df,id.vars = c(1,2,3))
  df_rfrz_m <- melt(df_rfrz,id.vars = c(1,2,3))
  df_runoff_m <- melt(df_runoff,id.vars = c(1,2,3))


  get_palette<- colorRampPalette(brewer.pal(brewer.pal.info[ pal_name,1], pal_name))
  cbp1<-get_palette(9)
  
# Plotting
if (opt=="normal"){

  
  pList <- lapply(1:length(year_list), function(i){ 
    p <- ggplot()+
      geom_line(data=df_m[(year(date_mod)==year_list[i] &
                                  month(date_mod) %in% 5:9),],
                aes(x = date_mod, 
                    y = value,
                    group = variable, 
                    color = variable))+
      labs(x = "", y = "")+
      scale_color_manual(values = cbp1[i_mod])+
      scale_y_continuous(limits=set_lim,  expand=c(0.02,0.01))+
      scale_x_datetime(limits = as.POSIXct(c(paste(year_list[i],"-05-01",sep=""),
                                             paste(year_list[i],"-09-01",sep=""))) ,
                                           expand=c(0.02,0.01),
                       labels = if (length(year_list)>1) {date_format("%b", tz = "CET")} else {date_format("%b-%Y", tz = "CET")})+
      annotate('text', 
               x = as.POSIXct(paste(year_list[i],"-05-03",sep="")),
               y = 0.9*set_lim[2], 
               label = if (length(year_list)>1) {year_list[i]} else {element_blank()},
               hjust=0)+
      labs(color="Model")+
      theme(axis.text.x = if (i<length(year_list)) {element_blank()} else {},
            axis.title.x = element_blank(),
            axis.title.y = element_blank(),
            panel.background = element_blank(),
            axis.line = element_line(colour = "black"),
            panel.border = element_rect(colour = "black", fill=NA, size=1),
            legend.position = if (i==1){c(1.05,0.5)} else {"none"},
            legend.justification = c(0,1),
            legend.key=element_rect(colour=NA,fill=NA))
  })
  
 h_final<- grid.arrange(grobs=pList, 
               ncol=max(1,floor(length(year_list)/5)),
               top=sites[[i_site]], 
               left= if (var_name=="trfrz") {"Refreezing (mm w.eq.)"} else
                     if (var_name=="tfac") {"Firn air content (m)"} else
                     if (var_name=="trunoff") {"Runoff (mm w.eq.)"} else
                     if (var_name=="tlwc") {"Liquid water content (mm w.eq.)"},
               bottom="Month",
               vp=viewport(x=0, just="left", width=0.7, height=1))
  ggsave(filename=paste0("Plots/",sites[[i_site]],"_",var_name,"_",
                             paste(models[i_mod],collapse='_'),"_yby.jpg"),
             plot=h_final, 
         device = "jpeg",
         height = 2.5, 
          width = 5)
  i=1
  p_out <- ggplot()+
      geom_line(data=df_m[(year(date_mod)==year_list[i] &
                                  month(date_mod) %in% 5:9),],
                aes(x = date_mod, 
                    y = value,
                    group = variable, 
                    color = variable))+
      labs(x = "", y = "")+
      scale_color_manual(values = cbp1[i_mod])+
      scale_y_continuous(limits=set_lim,  expand=c(0.02,0.01))+
      scale_x_datetime(limits = as.POSIXct(c(paste(year_list[i],"-05-01",sep=""),
                                             paste(year_list[i],"-09-01",sep=""))) ,
                                           expand=c(0.02,0.01),
                       labels = date_format("%b-%Y", tz = "CET"))+
      labs(color="Model")+
          theme(panel.background = element_blank(),
            axis.line = element_line(colour = "black"),
            panel.border = element_rect(colour = "black", fill=NA, size=1),
            legend.key=element_rect(colour=NA,fill=NA))
  return(p_out)
}

if (opt=="yearly"){
  
    #Yearly totals:
    df_year <- data.frame(unique(df$year))
    colnames(df_year)[1] <- "year"
    df_rfrz_year <- df_year
    df_runoff_year <- df_year
    for (i in i_mod){
      df_year[,models[[i]][1]] <- accumarray(df$year-df$year[1]+1,
                                                  df[,models[[i]][1]],
                                             func=function (x) {sum(x,na.rm=TRUE)}) 
      df_rfrz_year[,models[[i]][1]] <- accumarray(df$year-df$year[1]+1,
                                                  df_rfrz[,models[[i]][1]],
                                             func=function (x) {sum(x,na.rm=TRUE)})
      df_runoff_year[,models[[i]][1]] <- accumarray(df$year-df$year[1]+1,
                                                    df_runoff[,models[[i]][1]],
                                             func=function (x) {sum(x,na.rm=TRUE)})
      
       df_year[,models[[i]][1]] <- df_year[,models[[i]][1]]/
        (df_runoff_year[,models[[i]][1]]+df_rfrz_year[,models[[i]][1]]) *100
    }
  
    df_year_m <- melt(df_year,id.vars = 1)
    h_yearly<- ggplot(data = df_year_m, 
                      aes(x=year,
                          y = value, 
                          group = variable, 
                          color=variable))+
      ggtitle(sites[[i_site]])+
      geom_point(size=2)+
      geom_line() +
      labs(x = "Year", 
           y =  if (var_name=="trfrz") {expression(atop("Yearly refreezing",
                                                        paste("(mm w.eq.)")))} else
                if (var_name=="tfac") {"Yearly firn air content (m)"} else
                if (var_name=="trunoff") {expression(atop("Yearly runoff",
                                                        paste("(mm w.eq.)")))} else
                if (var_name=="tlwc") {"Yearly liquid water content (mm w.eq.)"},
           color="Model")+
      scale_color_manual(values = cbp1)+
      scale_x_continuous(expand=c(0.01,0.01))+
      scale_y_continuous(expand=c(0.01,0.01))+
      theme(panel.background = element_blank(),
              axis.line = element_line(colour = "black"),
              panel.border = element_rect(colour = "black", fill=NA, size=1),
            legend.key=element_rect(colour=NA,fill=NA))
    plot(h_yearly)
    ggsave(filename=paste0("Plots/",sites[[i_site]],"_",var_name,"_",
                             paste(models[i_mod],collapse='_'),"_yearly.jpg"),
          plot=h_yearly,
           device = "jpeg",
           height = 2.5, 
          width = 5)
      return(h_yearly)
}
  
  if (opt=="yearly_average"){
  
    #Yearly totals:
    df_year <- data.frame(unique(df$year))
    colnames(df_year)[1] <- "year"

    for (i in i_mod){
      df_year[,models[[i]][1]] <- accumarray(df$year-df$year[1]+1,df[,models[[i]][1]], func=function (x) {mean(x,na.rm=TRUE)}) }
  
      # for (i in i_mod){print(models[[i]][1])}

    df_year_m <- melt(df_year,id.vars = 1)
    h_yearly<- ggplot(data = df_year_m, 
                      aes(x=year,
                          y = value, 
                          group = variable, 
                          color=variable))+
      geom_point(size=2)+
      geom_line() +
      labs(x = "Year", 
           y = if (var_name=="trfrz") {"Annual average refreezing (mm w.eq.)"} else
             if (var_name=="tfac") {"Firn air content (m)"} else
               if (var_name=="trunoff") {"Annual average runoff (mm w.eq.)"} else
                 if (var_name=="tlwc") {"Annual average liquid water content (mm w.eq.)"},
           color="Model")+
      scale_color_manual(values = cbp1)+
      scale_x_continuous(expand=c(0,0))+
      scale_y_continuous(expand=c(0,0),limits=set_lim)+
      ggtitle(sites[[i_site]])+
      theme(panel.background = element_blank(),
              axis.line = element_line(colour = "black"),
              panel.border = element_rect(colour = "black", fill=NA, size=1),
            legend.key=element_rect(colour=NA,fill=NA))
    
      plot(h_yearly)
    
      ggsave(filename=paste0("Plots/",sites[[i_site]],"_",var_name,"_",
                             paste(models[i_mod],collapse='_'),"_yearly.jpg"),
             plot=h_yearly,device = "jpeg")
    
      return(h_yearly)

}

if(opt=="all"){
  h_all<- ggplot()+geom_line(data=df_m,
                aes(x = date_mod, 
                    y = value,
                    group = variable, 
                    color=variable))+
          scale_color_manual(values = cbp1[i_mod])
  plot(h_all)
      return(h_all)


}

}

```



```{r trunoff KANU yearly1}
library(cowplot)
h1 <- multi_1D_plot(i_site=1,i_mod=c(1,2,3,4,5,6,7,8,9), 
              var_name = 'trunoff',  
              multipl_fact=1,
              opt="yearly",
              pal_name='Set1',
              set_lim=100)

h1 <- h1 + guides(color=guide_legend(ncol=5))

mylegend<-as_ggplot(get_legend(h1))

h1<-h1 +theme(legend.position = "none")+
    scale_y_continuous(name = "Runoff [%]",
                            sec.axis = sec_axis(~100-.*1, 
                                                name = "Refreezing [%]")) +
    coord_cartesian(ylim = c(0, 100))
h1
h2<-multi_1D_plot(i_site=2,i_mod=c(1,2,3,4,5,6,7,8,9), 
              var_name = 'trunoff',  
              multipl_fact=1,
              opt="yearly",
              pal_name='Set1')  
h2<-h2 +theme(legend.position = "none") +
    scale_y_continuous(name = "Runoff [%]",
                            sec.axis = sec_axis(~100-.*1, 
                                                name = "Refreezing [%]")) +
    coord_cartesian(ylim = c(0, 100))

title <- ggdraw() + 
  draw_label( "",     fontface = 'bold',    x = 0,    hjust = 0  ) +
  theme(plot.margin = margin(0, 0, 0, 3))
h3 <- plot_grid(h1,h2, align = "hv", nrow = 1, 
                rel_widths = c(1,1),labels=c("a)","b)"))
h3
h <- plot_grid(mylegend, h3, align = "v", nrow = 2, rel_heights = c(0.8,2.4)) +
  theme(plot.margin = margin(10, 10, 10, 0))
h
ggsave(filename=paste0("Plots/KANU_runoff_rfrz.jpg"),
             plot=h,device = "jpeg")
```



```{r trunoff KANU yearbyyear2}
multi_1D_plot(i_site=1,i_mod=c(3,4), var_name = 'trunoff',  multipl_fact=1,pal_name='Set1')  
```

No runoff at KANU in IMAUFDM, UppsalaUni

```{r trfrz KANU yearbyyear1}
multi_1D_plot(i_site=1,i_mod=1:3, var_name = 'trfrz',  multipl_fact=1)  
```

```{r trfrz KANU yearbyyear2}
multi_1D_plot(i_site=1,i_mod=c(4,6,9), var_name = 'trfrz',  multipl_fact=1)  
```

```{r trfrz KANU yearbyyear3}
multi_1D_plot(i_site=1,i_mod=c(5,7,8), var_name = 'trfrz',  multipl_fact=1)  
```

```{r trunoff Dye2 long yearly1}
multi_1D_plot(i_site=2,i_mod=c(1,2,3,4,6,9), var_name = 'trunoff',  multipl_fact=1,opt="yearly")  
```

 
No runoff at Dye 2 in IMAUFDM, UppsalaUniBucket and UppsalaUniDeepPerc.


```{r trfrz  Dye2 long yearly}
multi_1D_plot(i_site=2,i_mod=1:9, var_name = 'trfrz',  multipl_fact=1,opt="yearly")  
```

```{r trfrz Dye2 16 yearbyyear1}
multi_1D_plot(i_site=3,i_mod=1:3, var_name = 'trfrz',  multipl_fact=1)  
```

```{r trfrz Dye2 16 yearbyyear2}
multi_1D_plot(i_site=3,i_mod=c(4,6,9), var_name = 'trfrz',  multipl_fact=1)  
```

```{r trfrz Dye2 16 yearbyyear3}
multi_1D_plot(i_site=3,i_mod=c(5,7,8), var_name = 'trfrz',  multipl_fact=1)  
```


```{r trfrz  Summit yearly}
multi_1D_plot(i_site=4,i_mod=1:9, var_name = 'trfrz',  multipl_fact=1,opt="yearly")  
```

```{r trunoff Summit yearly}
multi_1D_plot(i_site=4,i_mod=1:9, var_name = 'trunoff',  multipl_fact=1,opt="yearly")  
```

```{r trfrz FA yearbyyear1}
multi_1D_plot(i_site=5,i_mod=1:3, var_name = 'trfrz',  multipl_fact=1)  
```

```{r trfrz FA yearbyyear2}
multi_1D_plot(i_site=5,i_mod=c(4,6,9), var_name = 'trfrz',  multipl_fact=1)  
```

```{r trfrz FA yearbyyear3}
multi_1D_plot(i_site=5,i_mod=c(7,8), var_name = 'trfrz',  multipl_fact=1)  
```

```{r trunoff FA yearbyyear1}
multi_1D_plot(i_site=5,i_mod=1:3, var_name = 'trunoff',  multipl_fact=1)  
```

```{r trunoff FA yearbyyear2}
multi_1D_plot(i_site=5,i_mod=1:4, var_name = 'trunoff',set_lim=c(0,2),  multipl_fact=1)  
```

```{r trunoff FA yearbyyear3}
multi_1D_plot(i_site=5,i_mod=c(5,7,8), var_name = 'trunoff', set_lim=c(0,0.1), multipl_fact=1)  
```



```{r tlwc KANU yearbyyear}
multi_1D_plot(i_site=1,i_mod=1:2, var_name = 'tlwc',  multipl_fact=1)  
```

```{r tlwc Dye2 yearbyyear}
multi_1D_plot(i_site=3,i_mod=3:4, var_name = 'tlwc',  set_lim = c(0,200),multipl_fact=1)  
```

```{r tlwc FA yearbyyear}
 
margin <- c(1,6,3,1)/6


h2<-multi_1D_plot(i_site=5,i_mod=1:9, var_name = 'tlwc',  multipl_fact=1) +
  guides(color=guide_legend(ncol=5)) +
  labs(x = "Year", 
           y =  expression(atop("Liquid water ", paste("content (mm w.eq.)"))))

h1 <- as_ggplot(get_legend(h2))

h2<-h2 +theme(legend.position = "none",
              plot.title = element_blank(),
              plot.margin = unit(margin, "cm"),
              axis.title.x = element_blank(),
              axis.text.x=element_blank()) +
  draw_label( "a)", fontface = 'bold', x = as.POSIXct("2014-05-01"), y = 1500,  hjust = 0  )


h3<-multi_1D_plot(i_site=5,i_mod=1:9, var_name = 'trfrz',  multipl_fact=1)  
h3<-h3 + theme(legend.position = "none",
               plot.title = element_blank(),
               plot.margin = unit(margin, "cm"),
               axis.title.x = element_blank(),
              axis.text.x=element_blank())+
          draw_label( "b)", fontface = 'bold', x = as.POSIXct("2014-05-01"), y = 1.5, hjust = 0  )+
  labs(x = "Year", 
           y =  expression(atop("Refreezing", paste("(mm w.eq.)"))))

h4<-multi_1D_plot(i_site=5,i_mod=1:9, var_name = 'trunoff',  multipl_fact=1)
h4<-h4 + theme(legend.position = "none",
               plot.title = element_blank(),
               plot.margin = unit(margin, "cm"))+
  draw_label( "c)",fontface = 'bold',x = as.POSIXct("2014-05-01"), y = 0.6,hjust = 0  )+
  labs(x = "Year", 
           y =  expression(atop("Runoff", paste("(mm w.eq.)"))))

h <- plot_grid(h1,h2,h3,h4, align = "v", nrow = 4, rel_heights = c(1,1.6,1.6,2))
h
ggsave(filename=paste0("Plots/FA_SMB.jpg"),
             plot=h,device = "jpeg")
```

```{r tfac  Dye2 yearly}

margin <- c(1,3,1,1)/6


h2<-multi_1D_plot(i_site=2,i_mod=1:9, var_name = 'tfac',  
              multipl_fact=1, opt="yearly_average",
              set_lim = c(0,30)) 
h2<-h2 +guides(color=guide_legend(ncol=5))

h1 <- as_ggplot(get_legend(h2))

h2<-h2 +theme(legend.position = "none",
              plot.title = element_blank(),
              plot.margin = unit(margin, "cm")) +
  draw_label( "a) Dye-2",     fontface = 'bold',    x = 1998.1, y = 27,  hjust = 0  )


h3<-multi_1D_plot(i_site=4,i_mod=1:9, var_name = 'tfac',  
              multipl_fact=1, opt="yearly_average",
              set_lim = c(0,30))  
h3<-h3 + theme(legend.position = "none",
               plot.title = element_blank(),
               plot.margin = unit(margin, "cm"))+
  draw_label( "b) Summit",     fontface = 'bold',    x = 2000.1, y = 5,    hjust = 0  )

h <- grid.arrange(h1,h2,h3,
                  heights =  c(1,2,2))
ggsave(filename=paste0("Plots/FAC_Dye2_Summit.jpg"),
             plot=h,device = "jpeg")
```





