---
title: "R Notebook"
output:
  html_document:
    highlight: textmate
    theme: spacelab
    toc: yes
  pdf_document:
    toc: yes
  html_notebook:
    toc: yes
  word_document:
    toc: yes
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plotly)
library(akima)
library(ncdf4)
library(ggplot2)
library(reshape)
library(functional)
library(pracma)
library(dplyr)
library(lubridate)
library(gridExtra)
library(grid)
library(fields)

Sys.setenv("plotly_username"="BaptisteV")
Sys.setenv("plotly_api_key"="7U99HT4nSOGDBKwUveT6")

path_model<-'C:/Users/bav/OneDrive - Geological survey of Denmark and Greenland/Data/RetMIP/Model outputs/'
sites<-list('KANU','Dye-2_long','Dye-2_16','Summit','FA')
models <- list('CFM-Cr','CFM-KM','DTU','DMIHH','GEUS','IMAUFDM','MeyerHewitt','UppsalaUniBucket','UppsalaUniDeepPerc')
start_time <- c("01-May-2012 00:00:00","01-Jun-1998 00:00:00","02-May-2016 00:00:00","02-Jul-2000 00:00:00","12-Apr-2014 00:00:00")
end_time <- c("31-Dec-2016 06:00:00","02-May-2015 15:00:00","28-Oct-2016 09:00:00","08-Mar-2015 12:00:00","02-Dec-2014 21:00:00")



Time2Posix <- function (orig_time,  time_in, timez='UTC'){
  	days = time_in - as.numeric( as.Date("1970-01-01")  - as.Date(orig_time))
  	# - 719529 	# 719529 = days from 1-1-0000 to 1-1-1970
	  secs = days * 86400 # 86400 seconds in a day
	return(as.POSIXct(strftime(
	  as.POSIXct(secs, origin = "1970-01-01", 
			tz = 'UTC'), format = '%Y-%m-%d %H:%M', 
			tz = 'UTC', usetz = FALSE), tz = timez))
}

```

This document contains the scripts and plots for the RetMIP project (http://retain.geus.dk/index.php/retmip/).

```{r Percolation depth}
# loading data
file_path <- "C:\\Users\\bav\\OneDrive - Geological survey of Denmark and Greenland\\Data\\RetMIP\\Validation datasets\\UpGPR_Dye2_Heilig\\"
filename <- "PercolationDepth_m_Perco2016.csv"
d_perc <- read.table(paste0(file_path,filename), header = FALSE, sep = ",", dec = ".")
d_perc$time <-     as.POSIXct((d_perc$V1 - 719529)*86400, origin = "1970-01-01", tz = "UTC")

i_site <- 3
var_name <- 'lwc'
offset <- 0
multipl_fact<-1

 for (i_mod in 1:9){
    file_name_col <- paste('RetMIP_',models[i_mod],'_',sites[i_site],'_3hourly_columns.nc',sep = "")
    path_file_col<-paste(path_model,models[i_mod],'/',file_name_col,sep = "")
    
    # loading column data
    file_nc_col<- nc_open(path_file_col)
    var_mod <- ncvar_get(file_nc_col, varid=var_name)
    var_mod <- var_mod + offset
    var_mod <- var_mod *multipl_fact
    
    if (i_mod == 6)
      {var_mod <- var_mod[!is.na(var_mod[,1]),]}
    # if (i_mod == 5 & var_name == "temp")
    # {var_mod <- var_mod +273}
    
    if (i_mod == 5 & var_name == "lwc")
      { var_mod<- pmax(var_mod,0)}
    # {var_mod <- var_mod +273}
    
    if (i_mod %in% 1:3 & var_name == "lwc")
      { var_mod<- var_mod*1000}
    
    if (dim(var_mod)[1]>dim(var_mod)[2]) var_mod <- t(var_mod)
    
    time1<-1:dim(var_mod)[2]
    
    date_mod<-seq(lubridate::dmy_hms(start_time[i_site]),
      lubridate::dmy_hms(end_time[i_site]),
      3600*3)
    
    if (length(date_mod)<length(time1)) {
      var_mod<-var_mod[,- (1:(length(time1)-length(date_mod)))]
      time1  <- time1[- (1:(length(time1)-length(date_mod)))]}
    
    if (length(date_mod)>length(time1)) {
      print(length(date_mod))
      print(length(time1))
      time <- ncvar_get(file_nc_col, varid='time')
      time<- time*3600*24 + as.POSIXct("1900-01-01")
    }
    
    while (length(date_mod)>length(time1)) {
      time1 <- append(time1, time1[length(time1)]+3600*3)
      var_mod <- cbind(var_mod, var_mod[,length(time1)-1])}
    
    # some filtering
    # var_mod<-var_mod[apply(var_mod, 1, Compose(is.finite, all)),]
    
    # rearranging in xyz array
    ind_select<-seq(1,dim(var_mod)[2],max(1,floor(dim(var_mod)[2]/1000)))
    time_select <- date_mod[ind_select]
    var_mod<-var_mod[,ind_select]
    d_perc_mod  <- var_mod[1,ind_select]*0
    depth <- seq(0.1, 20, 0.1)
     for (i in 1:length(d_perc_mod)){
       if (length(which(var_mod[,i] > 0.0000001))>0)
         {
         ind <- max(which(var_mod[,i] > 0.0000001))
         d_perc_mod[i] <- depth[ind]
          }
     }
       
    if (i_mod==1) {
      df <- data.frame(time_select,cbind(d_perc_mod))
      colnames(df)[0] <- "time"} 
    else {df <- cbind(df,d_perc_mod)}
    colnames(df)[1+i_mod] <- models[i_mod]
  }

```


``` {r plotting with plotly}
library(RColorBrewer)
pal_name <- "Set1"

p1 <- plot_ly(df, x = ~time_select) %>%
    layout(xaxis = list(title = "Year"),
         yaxis = list (title = "Percolation depth (m)",autorange = "reversed"))

p2 <- plot_ly(df, x = ~time_select) %>%
    layout(xaxis = list(title = "Year"),
         yaxis = list (title = "Percolation depth (m)",
                       range = c(5,0)))

p3 <- plot_ly(df, x = ~time_select) %>%
    layout(xaxis = list(title = "Year"),
         yaxis = list (title = "Percolation depth (m)",
                       range = c(5,0)))

# list of the column to be plotted

  get_palette<- colorRampPalette(brewer.pal(brewer.pal.info[ pal_name,1], pal_name))
  cbp1<-get_palette(9)
  
for(i in c(1,2,3)){
  p1 <- p1 %>% add_trace(x = df[["time_select"]], y = df[[i+1]], 
                       name = models[[i]],
                       type = 'scatter',
                       mode = 'lines',
                       line = list(width = 2,color=cbp1[i]))
}
for(i in c(4,5,6)){
  p2 <- p2 %>% add_trace(x = df[["time_select"]], y = df[[i+1]], 
                       name = models[[i]],
                       type = 'scatter',
                       mode = 'lines',
                       line = list(width = 2,color=cbp1[i]))
}
for(i in c(7,8,9)){
  p3 <- p3 %>% add_trace(x = df[["time_select"]], y = df[[i+1]], 
                       name = models[[i]],
                       type = 'scatter',
                       mode = 'lines',
                       line = list(width = 2,color=cbp1[i]))
}

p1 <- p1 %>% add_trace(x = d_perc$time, y = d_perc$V2, name = "Up-GPR",
                       mode = 'lines',
                     showlegend = FALSE,
                     type = 'scatter',
                       line = list(color='black',width = 4))
p2 <- p2 %>% add_trace(x = d_perc$time, y = d_perc$V2, name = "Up-GPR",
                       mode = 'lines',   
                     showlegend = FALSE,
                     type = 'scatter',
                       line = list(color='black',width = 4))
p3 <- p3 %>% add_trace(x = d_perc$time, y = d_perc$V2, name = "Up-GPR",
                       mode = 'lines',   
                     type = 'scatter',
                       line = list(color='black',width = 4))

p1 <- p1 %>% add_trace(data, x = d_perc$time[1], y = 2, type = 'scatter',
        mode = 'text', text = "<b>a)<b>", textposition = 'middle right',
        showlegend = FALSE,
                     textfont = list(color = '#000000', size = 16)) 
p2 <- p2 %>% add_trace(data, x = d_perc$time[1], y = 1, type = 'scatter',
        mode = 'text', text = "<b>b)<b>", textposition = 'middle right',
        showlegend = FALSE,
                     textfont = list(color = '#000000', size = 16)) 
p3 <- p3 %>% add_trace(data, x = d_perc$time[1], y = 1, type = 'scatter',
        mode = 'text', text = "<b>c)<b>", textposition = 'middle right',
        showlegend = FALSE,
                     textfont = list(color = '#000000', size = 16)) 

p<- subplot(p1,p2,p3, nrows = 3,shareX = TRUE)
p <- p %>% layout(yaxis2 = list (title = "Percolation depth (m)",
                       range = c(5,0)))
p
plotly_IMAGE(p, format = "png", out_file = paste0("Plots/percolation_depth_val.png"),width = 600, height = 400,scale=10)

```